-- =============================================================================
-- Migration 001: Initial Schema
-- Origami — Autonomous Content Creation Agent
-- =============================================================================

-- Users are handled entirely by Supabase Auth (auth.users table).
-- We reference auth.users via user_id foreign keys but never manage
-- user rows ourselves.

-- ---------------------------------------------------------------------------
-- projects
-- Each row represents one "channel/niche" the agent manages autonomously.
-- ---------------------------------------------------------------------------
create table projects (
  id                  uuid        primary key default gen_random_uuid(),
  user_id             uuid        references auth.users not null,
  name                text        not null,               -- e.g. "AI Tech Reviews"
  niche_keywords      text[]      not null,               -- e.g. ["AI", "LLMs", "tech news"]
  brand_voice_prompt  text        not null,               -- fragment injected into system prompts
  content_style       text        not null,               -- "long-form" | "short-form" | "thread" | "carousel"
  video_style         text,                               -- "text-overlay" | "stock-footage" | "avatar"
  approval_mode       text        not null default 'manual', -- "manual" | "auto"
  posting_schedule    jsonb       not null,               -- { "cron": "0 10 * * *", "timezone": "Asia/Kolkata" }
  active              boolean     not null default true,
  created_at          timestamptz not null default now()
);

comment on table projects is
  'One row per project (channel/niche). Each project runs an independent daily pipeline.';
comment on column projects.approval_mode is
  'manual = Telegram approval gate before publish. auto = publish directly, send daily digest.';
comment on column projects.posting_schedule is
  'JSONB with shape { cron: string, timezone: string }. Parsed by n8n scheduler.';

-- ---------------------------------------------------------------------------
-- project_platforms
-- Per-project OAuth credentials and settings for each target platform.
-- ---------------------------------------------------------------------------
create table project_platforms (
  id                    uuid    primary key default gen_random_uuid(),
  project_id            uuid    references projects on delete cascade not null,
  platform              text    not null,     -- "youtube" | "instagram" | "x"
  account_handle        text,                 -- human-readable handle for display
  credentials_encrypted jsonb,               -- encrypted OAuth tokens (never raw, see encryption layer)
  enabled               boolean not null default true,
  unique (project_id, platform)
);

comment on table project_platforms is
  'Platform-specific configuration and encrypted credentials per project.';
comment on column project_platforms.credentials_encrypted is
  'OAuth tokens encrypted at the application layer before storage. The encryption key is never stored in Supabase.';

-- ---------------------------------------------------------------------------
-- content_pieces
-- Each row is one piece of content generated by the agent pipeline.
-- ---------------------------------------------------------------------------
create table content_pieces (
  id                  uuid        primary key default gen_random_uuid(),
  project_id          uuid        references projects on delete cascade not null,
  topic               text        not null,
  angle               text,                               -- unique angle / hook
  script              text,                               -- full script or thread body
  caption             text,                               -- platform caption
  hashtags            text[],                             -- array of hashtag strings (without #)
  thumbnail_url       text,                               -- R2 signed URL or public URL
  video_url           text,                               -- R2 signed URL or public URL
  status              text        not null default 'draft',
                                                          -- draft | pending_approval | approved |
                                                          -- rejected | published | failed
  platforms_published jsonb       not null default '{}',  -- { "youtube": "video_id", "x": "post_id" }
  created_at          timestamptz not null default now(),
  scheduled_for       timestamptz,
  published_at        timestamptz
);

comment on table content_pieces is
  'One row per generated content item. Tracks full lifecycle from draft to published.';
comment on column content_pieces.status is
  'Lifecycle: draft → pending_approval → approved → published. Or → rejected / failed.';
comment on column content_pieces.platforms_published is
  'Map of platform → platform-specific content ID, populated after successful publish.';

-- ---------------------------------------------------------------------------
-- content_analytics
-- Engagement metrics pulled back from each platform 24h after publish.
-- ---------------------------------------------------------------------------
create table content_analytics (
  id                uuid        primary key default gen_random_uuid(),
  content_piece_id  uuid        references content_pieces on delete cascade not null,
  platform          text        not null,   -- "youtube" | "instagram" | "x"
  views             integer     not null default 0,
  likes             integer     not null default 0,
  comments          integer     not null default 0,
  shares            integer     not null default 0,
  ctr               numeric,               -- click-through rate (YouTube-specific, percentage)
  reach             integer,               -- unique accounts reached (IG-specific)
  fetched_at        timestamptz not null default now()
);

comment on table content_analytics is
  'Engagement metrics per platform per content piece. Fed back into topic selector next day.';

-- ---------------------------------------------------------------------------
-- trend_cache
-- Raw trend payloads cached to avoid repeated API calls within 6 hours.
-- ---------------------------------------------------------------------------
create table trend_cache (
  id              uuid        primary key default gen_random_uuid(),
  source          text        not null,   -- "google_trends" | "reddit" | "x" | "youtube"
  niche_keywords  text[]      not null,
  payload         jsonb       not null,
  fetched_at      timestamptz not null default now()
);

comment on table trend_cache is
  'Cached trend API responses. TTL = 6 hours, enforced by n8n workflow query logic.';
comment on column trend_cache.payload is
  'Raw merged output from the trend research service. Schema varies by source.';
